// Types
export type { Character, Lookbook, Look, Persona, CharacterImage, SkillVideo, SkillImage, Generation } from "./types";
// Backward compat aliases
export type { Verse, VerseCharacter } from "./types";

// Manual data (base, rarely changes)
export { CHARACTERS, CHARACTERS_BY_ID, createCharactersById } from "./characters";
export { LOOKBOOKS, LOOKBOOKS_BY_ID } from "./lookbooks";
export { LOOKS, LOOKS_BY_ID, getLooksByLookbook } from "./looks";
export { PERSONAS, getPersonas, buildPersonaMap } from "./personas";
export { TRACKS, TRACKS_BY_ID } from "./tracks";

// Backward compat aliases
export { LOOKBOOKS as VERSES, LOOKBOOKS_BY_ID as VERSES_BY_ID } from "./lookbooks";
export { PERSONAS as VERSE_CHARACTERS } from "./personas";
export { getPersonas as getVerseCharacters } from "./personas";
export { buildPersonaMap as buildVerseCharacterMap } from "./personas";

// Synced data (auto-generated by sync-public.ts)
export { SYNCED_LOOKBOOKS, SYNCED_LOOKBOOKS as SYNCED_VERSES } from "./synced-lookbooks";
export { SYNCED_PERSONAS, SYNCED_PERSONAS as SYNCED_VERSE_CHARACTERS } from "./synced-personas";
export { SYNCED_LOOKS } from "./synced-looks";
export { SYNCED_SKILL_VIDEOS } from "./synced-skill-videos";
export { SYNCED_SKILL_IMAGES } from "./synced-skill-images";
export { SYNCED_CHARACTER_IMAGES } from "./synced-character-images";
export { SYNCED_GENERATIONS } from "./synced-generations";
