// Auto-generated by scripts/sync-public.ts — DO NOT EDIT MANUALLY
import type { Verse } from "./types";

export const SYNCED_VERSES: Verse[] = [
  {
    "id": "00",
    "name": "sleek concept",
    "displayName": "sleek concept",
    "description": "SLEEK CONCEPT 입니다.",
    "displayOrder": 0
  },
  {
    "id": "01",
    "name": "ojos collaboration",
    "displayName": "Ojos collaboration",
    "description": "OJOS COLLABORATION 입니다.",
    "displayOrder": 1
  }
];
