// Auto-generated by scripts/sync-public.ts — DO NOT EDIT MANUALLY
import type { SkillVideo } from "./types";

export const SYNCED_SKILL_VIDEOS: SkillVideo[] = [
  {
    "id": "3d38c51c-a601-41ef-9cce-c555db6fe982",
    "name": "Subway",
    "videoUrl": "/skills/videos/1769777143290-trim_subway_action_lego.mp4",
    "thumbnailUrl": "/skills/thumbnails/1769777143628-trim_subway_action_lego.jpg",
    "duration": 7.80399
  },
  {
    "id": "b04b87c2-b752-49b0-b889-7001c8dc1973",
    "name": "Smile",
    "videoUrl": "/skills/videos/1769775024747-11.mp4",
    "thumbnailUrl": "/skills/thumbnails/1769775025259-11.jpg",
    "duration": 9.76302
  },
  {
    "id": "1481ab13-4588-4ce3-a29b-3ba2ce8050c9",
    "name": "Above",
    "videoUrl": "/skills/videos/1769774972931-10.mp4",
    "thumbnailUrl": "/skills/thumbnails/1769774973134-10.jpg",
    "duration": 3.89955
  },
  {
    "id": "93d05791-79b7-4df7-8c9b-8f93342116a6",
    "name": "Hip",
    "videoUrl": "/skills/videos/1769774789728-10.mp4",
    "thumbnailUrl": "/skills/thumbnails/1769774790190-10.jpg",
    "duration": 9.58801
  },
  {
    "id": "29fc1475-7dc7-417e-bfc4-dc60e54a6b71",
    "name": "Cute Action",
    "videoUrl": "/skills/videos/1769773766955-09.mp4",
    "thumbnailUrl": "/skills/thumbnails/1769773767453-09.jpg",
    "duration": 9.22801
  },
  {
    "id": "e23b3a70-37d3-4b2a-a994-d0f35ed61b74",
    "name": "Dance",
    "videoUrl": "/skills/videos/1769773533936-08.mp4",
    "thumbnailUrl": "/skills/thumbnails/1769773534398-08.jpg",
    "duration": 9.48301
  },
  {
    "id": "1e23a6ca-df07-4916-840f-5650b6f3a2e6",
    "name": "Touch",
    "videoUrl": "/skills/videos/1769771618505-03.mp4",
    "thumbnailUrl": "/skills/thumbnails/1769771619266-03.jpg",
    "duration": 9.66701
  },
  {
    "id": "c80339fd-4aa2-4e0c-ac84-4c788a468c4d",
    "name": "Runway",
    "videoUrl": "/skills/videos/1769767991728-on my way to 2026 - edit by @ksyush.ai the best.mp4",
    "thumbnailUrl": "/skills/thumbnails/1769767992290-on my way to 2026 - edit by @ksyush.ai the best.jpg",
    "duration": 6.84848
  },
  {
    "id": "fc28b740-9f6c-4efa-b09a-4a9565c81d99",
    "name": "Eat",
    "videoUrl": "/skills/videos/1769747475944-06.mp4",
    "thumbnailUrl": "/skills/thumbnails/1769747476251-06.jpg",
    "duration": 8.0327
  },
  {
    "id": "f1b6292c-ac7b-4e26-9a51-dce3738a1ddb",
    "name": "700k",
    "videoUrl": "/skills/videos/1769731717953-04.mp4",
    "thumbnailUrl": "/skills/thumbnails/1769731718385-04.jpg",
    "duration": 9.27402
  }
];
