// Auto-generated by scripts/sync-public.ts — DO NOT EDIT MANUALLY
import type { VerseCharacter } from "./types";

export const SYNCED_VERSE_CHARACTERS: VerseCharacter[] = [
  {
    "id": "b07fb8cf-a6e2-41cb-a264-38a7d07af66a",
    "verseId": "00",
    "characterId": "sumin",
    "name": "Sumin",
    "description": "미드 웬즈데이에서 영감을 받은 수민의 멀티 페르소나. 웬즈데이의 움직임을 연상케하는 왁킹 댄스 스킬이 주특기.",
    "video": "/character/00_sumin.mp4",
    "poster": "/character/00_sumin.png",
    "defaultInput": null,
    "displayOrder": 0
  },
  {
    "id": "18437a51-f762-4ce0-b252-0175548012aa",
    "verseId": "01",
    "characterId": "sumin",
    "name": "Sumin",
    "description": "OJOS의 세계관에서 영감을 받은 수민의 멀티 페르소나. 해체된 고프코어 룩 위에서 바랜 빈티지 무브먼트를 현대적으로 재해석하는 프리스타일이 특징.",
    "video": "/character/01_sumin.mp4",
    "poster": "/character/01_sumin.png",
    "defaultInput": null,
    "displayOrder": 0
  },
  {
    "id": "79b19004-8524-4d04-825f-78028d1392a3",
    "verseId": "01",
    "characterId": "rumi",
    "name": "Rumi",
    "description": "OJOS의 큐레토리얼 미학을 체현하는 루미의 멀티 페르소나. 잊혀진 오브제들 사이를 무표정으로 떠도는 공간 설치 아티스트. '진열이 아닌 전시'를 몸소 증명하는 존재.",
    "video": "/character/01_rumi.mp4",
    "poster": "/character/01_rumi.png",
    "defaultInput": null,
    "displayOrder": 1
  },
  {
    "id": "8958b8a6-898f-4558-9d03-5b66ef0baed7",
    "verseId": "00",
    "characterId": "rumi",
    "name": "Rumi",
    "description": "공포영화 장화, 홍련에서 영감을 받은 루미의 멀티 페르소나. 장화, 홍련 자매의 숨겨진 셋째 딸. 어던 퍼포먼스에서도 일관되게 귀신에 홀린듯한 무표정이 특징.",
    "video": "/character/00_rumi.mp4",
    "poster": "/character/00_rumi.png",
    "defaultInput": null,
    "displayOrder": 1
  },
  {
    "id": "c83ebbad-9d14-4e5c-a09b-dcbaf6115e53",
    "verseId": "00",
    "characterId": "geumbi",
    "name": "Geumbi",
    "description": "드라마 스카이캐슬에서 영감을 받은 금비의 멀티 페르소나. 기교 없이 귀에 꽂히는 보컬 스킬은 '수능 금지곡'을 만들어내는 데에 적합.",
    "video": "/character/00_geumbi.mp4",
    "poster": "/character/00_geumbi.png",
    "defaultInput": null,
    "displayOrder": 2
  },
  {
    "id": "f310fbf2-6727-41b1-b5df-8a3be888e18d",
    "verseId": "01",
    "characterId": "geumbi",
    "name": "Geumbi",
    "description": "OJOS의 유틸리타리안 감성을 보컬로 해석하는 금비의 멀티 페르소나. 가공 없는 날것의 보이스는 낡은 카세트에서 흘러나오는 듯한 로우파이 질감이 특징.",
    "video": "/character/01_geumbi.mp4",
    "poster": "/character/01_geumbi.png",
    "defaultInput": null,
    "displayOrder": 2
  },
  {
    "id": "36e614e7-e062-4972-8c6d-5ec3c3b128c8",
    "verseId": "00",
    "characterId": "jiyoon",
    "name": "Jiyoon",
    "description": "영국 밴드 오아시스에서 영감받은 지윤의 멀티 페르소나. 해당 페르소나의 콘텐츠들은 욕설이 난무해서 대부분 삐--- 소리로 오디오가 채워지는 경향이 있다. 일렉 기타 연주 스킬이 특징.",
    "video": "/character/00_jiyoon.mp4",
    "poster": "/character/00_jiyoon.png",
    "defaultInput": null,
    "displayOrder": 3
  },
  {
    "id": "7d1fc134-833f-4a05-b013-11a0abede20e",
    "verseId": "01",
    "characterId": "lei",
    "name": "Lei",
    "description": "OJOS의 기능주의 미학에 영감을 받은 레이의 멀티 페르소나. 유틸리티 웨어의 버클과 지퍼를 소품으로 활용하는 퍼포먼스와 실용적 움직임 속에 감춘 안무가 특징.",
    "video": "/character/01_lei.mp4",
    "poster": "/character/01_lei.png",
    "defaultInput": "/members/lei_10.png",
    "displayOrder": 3
  },
  {
    "id": "36be7942-02be-47f0-a55f-e249389fc21e",
    "verseId": "00",
    "characterId": "lei",
    "name": "Lei",
    "description": "류신레이의 멀티 페르소나. 비비안 웨스트우드 풍의 레스토랑에서 일하는 웨이트리스. 서빙 동작과 유사한 Bob Fosse Dance 스킬을 보유.",
    "video": "/character/00_lei.mp4",
    "poster": "/character/00_lei.png",
    "defaultInput": null,
    "displayOrder": 4
  },
  {
    "id": "b6e65fd3-569d-412e-afcb-0e08dafd7c6b",
    "verseId": "01",
    "characterId": "siori",
    "name": "Siori",
    "description": "OJOS의 '바랜 것에서 새로운 형태를 찾는' 철학을 시각으로 기록하는 시오리의 멀티 페르소나. 퇴색된 텍스처와 닳아가는 컬러를 필름에 담아내는 포토그래퍼.",
    "video": "/character/01_siori.mp4",
    "poster": "/character/01_siori.png",
    "defaultInput": null,
    "displayOrder": 4
  },
  {
    "id": "23840ba8-3a00-4628-a080-9a5a8a617e32",
    "verseId": "01",
    "characterId": "yui",
    "name": "Yui",
    "description": "OJOS의 '메시지가 제품에 앞선다'는 철학을 직물로 구현하는 유이의 멀티 페르소나. 데드스톡 원단을 해체하고 재조합하여 새로운 텍스타일을 창조하는 소재 디자이너.",
    "video": "/character/01_yui.mp4",
    "poster": "/character/01_yui.png",
    "defaultInput": null,
    "displayOrder": 5
  }
];
