// Auto-generated by scripts/sync-public.ts — DO NOT EDIT MANUALLY
import type { CharacterImage } from "./types";

export const SYNCED_CHARACTER_IMAGES: Record<string, CharacterImage[]> = {
  "geumbi": [
    {
      "id": "defa7557-9f6a-40c0-94d0-d73dc68684b2",
      "characterId": "geumbi",
      "variantId": "default",
      "storagePath": "geumbi.png",
      "publicUrl": "/members/geumbi.png"
    },
    {
      "id": "f3db549b-b4f6-403d-8549-e11e2077dbf4",
      "characterId": "geumbi",
      "variantId": "02",
      "storagePath": "geumbi_02.png",
      "publicUrl": "/members/geumbi_02.png"
    },
    {
      "id": "324656f3-90c1-4822-a7d6-bb5a71d8a0a1",
      "characterId": "geumbi",
      "variantId": "03",
      "storagePath": "geumbi_03.png",
      "publicUrl": "/members/geumbi_03.png"
    }
  ],
  "jiyoon": [
    {
      "id": "47ca5125-faf6-443f-9cd2-5b540b235794",
      "characterId": "jiyoon",
      "variantId": "default",
      "storagePath": "jiyoon.png",
      "publicUrl": "/members/jiyoon.png"
    },
    {
      "id": "f2f0a960-00fb-44ca-8682-b94db77c3336",
      "characterId": "jiyoon",
      "variantId": "02",
      "storagePath": "jiyoon_02.png",
      "publicUrl": "/members/jiyoon_02.png"
    }
  ],
  "lei": [
    {
      "id": "9af48ba0-aee3-473a-8905-60df7876bec8",
      "characterId": "lei",
      "variantId": "02",
      "storagePath": "lei_02.png",
      "publicUrl": "/members/lei_02.png"
    },
    {
      "id": "78702b3c-1c2b-443d-938e-a7317bee73c9",
      "characterId": "lei",
      "variantId": "03",
      "storagePath": "lei_03.png",
      "publicUrl": "/members/lei_03.png"
    },
    {
      "id": "9389ad70-910d-4ff6-a120-242e95be76e9",
      "characterId": "lei",
      "variantId": "04",
      "storagePath": "lei_04.png",
      "publicUrl": "/members/lei_04.png"
    },
    {
      "id": "b3cfe6ea-caaf-44ef-b7d9-6d54e7ccad3c",
      "characterId": "lei",
      "variantId": "05",
      "storagePath": "lei_05.png",
      "publicUrl": "/members/lei_05.png"
    },
    {
      "id": "83496597-f9e4-4a1c-8b97-c8b6d518a20c",
      "characterId": "lei",
      "variantId": "06",
      "storagePath": "lei_06.png",
      "publicUrl": "/members/lei_06.png"
    },
    {
      "id": "cab2ed07-5cbc-4a00-ae75-b0e26b9dbd00",
      "characterId": "lei",
      "variantId": "07",
      "storagePath": "lei_07.png",
      "publicUrl": "/members/lei_07.png"
    },
    {
      "id": "ebcf3ccd-7df7-42ad-b873-5fc1eb8f33e0",
      "characterId": "lei",
      "variantId": "08",
      "storagePath": "lei_08.png",
      "publicUrl": "/members/lei_08.png"
    },
    {
      "id": "f8f9e3a1-8fde-423a-9a09-ea67dbf97261",
      "characterId": "lei",
      "variantId": "09",
      "storagePath": "lei_09.png",
      "publicUrl": "/members/lei_09.png"
    },
    {
      "id": "595b1c02-8611-4d59-b8be-e7acc205abc8",
      "characterId": "lei",
      "variantId": "10",
      "storagePath": "lei_10.png",
      "publicUrl": "/members/lei_10.png"
    }
  ],
  "rumi": [
    {
      "id": "581836fa-fec8-4149-b70b-585bade0eb12",
      "characterId": "rumi",
      "variantId": "default",
      "storagePath": "rumi.png",
      "publicUrl": "/members/rumi.png"
    },
    {
      "id": "0d270439-c9fa-41ee-9ab2-d375802fa89e",
      "characterId": "rumi",
      "variantId": "02",
      "storagePath": "rumi_02.png",
      "publicUrl": "/members/rumi_02.png"
    },
    {
      "id": "efcccc9d-c8d0-4202-8ce7-ffbd25892f48",
      "characterId": "rumi",
      "variantId": "03",
      "storagePath": "rumi_03.png",
      "publicUrl": "/members/rumi_03.png"
    },
    {
      "id": "2cd82373-17f2-4cd3-abd0-4a95accc0a3d",
      "characterId": "rumi",
      "variantId": "04",
      "storagePath": "rumi_04.png",
      "publicUrl": "/members/rumi_04.png"
    },
    {
      "id": "06a4a8c4-c1a3-4816-b3e0-e768f27f67b0",
      "characterId": "rumi",
      "variantId": "05",
      "storagePath": "rumi_05.png",
      "publicUrl": "/members/rumi_05.png"
    }
  ],
  "sumin": [
    {
      "id": "86ca141f-22ec-440d-9db2-3603e7b01245",
      "characterId": "sumin",
      "variantId": "default",
      "storagePath": "sumin.png",
      "publicUrl": "/members/sumin.png"
    },
    {
      "id": "ee455f14-199f-4a4a-bff0-f56c37fd680c",
      "characterId": "sumin",
      "variantId": "02",
      "storagePath": "sumin_02.png",
      "publicUrl": "/members/sumin_02.png"
    },
    {
      "id": "91e514ea-2d38-4d01-971d-7989359036ad",
      "characterId": "sumin",
      "variantId": "03",
      "storagePath": "sumin_03.png",
      "publicUrl": "/members/sumin_03.png"
    }
  ]
};
