// Auto-generated by scripts/sync-public.ts — DO NOT EDIT MANUALLY
import type { Look } from "./types";

export const SYNCED_LOOKS: Look[] = [
  {
    "id": "00_01",
    "lookbookId": "00",
    "displayOrder": 0
  },
  {
    "id": "01_01",
    "lookbookId": "01",
    "displayOrder": 0
  },
  {
    "id": "00_02",
    "lookbookId": "00",
    "displayOrder": 1
  },
  {
    "id": "00_03",
    "lookbookId": "00",
    "displayOrder": 2
  },
  {
    "id": "00_04",
    "lookbookId": "00",
    "displayOrder": 3
  }
];
