// Auto-generated by scripts/sync-public.ts — DO NOT EDIT MANUALLY
import type { SkillImage } from "./types";

export const SYNCED_SKILL_IMAGES: SkillImage[] = [
  {
    "id": "674db884-7647-4649-ae7c-77f88272972e",
    "name": "Cat",
    "publicUrl": "/skills/concepts/1769771846607-You have to know about the photographer Wei Huan (@reihuannn) - he makes some super fun fashion .jpg"
  },
  {
    "id": "0f85f855-2754-4833-9758-db71801e69a1",
    "name": "Ice",
    "publicUrl": "/skills/concepts/1769771836465-Screenshot 2026-01-30 at 5.02.38 PM.png"
  }
];
