import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/_index.tsx"),
  route("login", "routes/login.tsx"),
  route("api/logout", "routes/api.logout.tsx"),
  route("api/download", "routes/api.download.tsx"),
  route("api/upload-motion", "routes/api.upload-motion.tsx"),
  route("api/delete-motion", "routes/api.delete-motion.tsx"),
  route("api/upload-character-image", "routes/api.upload-character-image.tsx"),
  route("api/delete-character-image", "routes/api.delete-character-image.tsx"),
  route("api/update-motion", "routes/api.update-motion.tsx"),
  route("api/upload-concept-image", "routes/api.upload-concept-image.tsx"),
  route("api/delete-concept-image", "routes/api.delete-concept-image.tsx"),
  route("api/update-concept-image", "routes/api.update-concept-image.tsx"),
  route("api/update-character", "routes/api.update-character.tsx"),
  route("api/update-lookbook", "routes/api.update-lookbook.tsx"),
  route("api/update-persona", "routes/api.update-persona.tsx"),
  route("api/library-data", "routes/api.library-data.tsx"),
  route("api/delete-run", "routes/api.delete-run.tsx"),
  route("api/editor-save", "routes/api.editor-save.tsx"),
  route("api/editor-media", "routes/api.editor-media.tsx"),
  route("api/workflow-templates", "routes/api.workflow-templates.tsx"),
  route("api/workflow-execute", "routes/api.workflow-execute.tsx"),
  route("api/soul-styles", "routes/api.soul-styles.tsx"),
  route("api/style-presets", "routes/api.style-presets.tsx"),
  route("api/personas", "routes/api.personas.tsx"),
  route("editor", "routes/editor.tsx"),
] satisfies RouteConfig;
