import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/_index.tsx"),
  route("login", "routes/login.tsx"),
  route("api/logout", "routes/api.logout.tsx"),
  route("api/generate", "routes/api.generate.tsx"),
  route("api/download", "routes/api.download.tsx"),
  route("api/upload-motion", "routes/api.upload-motion.tsx"),
  route("api/delete-motion", "routes/api.delete-motion.tsx"),
  route("api/delete-generation", "routes/api.delete-generation.tsx"),
  route("api/upscale", "routes/api.upscale.tsx"),
  route("api/upload-result", "routes/api.upload-result.tsx"),
  route("api/upload-character-image", "routes/api.upload-character-image.tsx"),
  route("api/delete-character-image", "routes/api.delete-character-image.tsx"),
  route("api/update-music", "routes/api.update-music.tsx"),
  route("api/update-motion", "routes/api.update-motion.tsx"),
  route("api/update-generation-motion", "routes/api.update-generation-motion.tsx"),
  route("api/upload-concept-image", "routes/api.upload-concept-image.tsx"),
  route("api/delete-concept-image", "routes/api.delete-concept-image.tsx"),
  route("api/generate-image", "routes/api.generate-image.tsx"),
  route("api/update-concept-image", "routes/api.update-concept-image.tsx"),
  route("api/update-generation-concept-image", "routes/api.update-generation-concept-image.tsx"),
  route("api/update-character", "routes/api.update-character.tsx"),
  route("api/update-lookbook", "routes/api.update-lookbook.tsx"),
  route("api/update-persona", "routes/api.update-persona.tsx"),
  route("api/gallery-data", "routes/api.gallery-data.tsx"),
  route("api/editor-save", "routes/api.editor-save.tsx"),
  route("api/workflow-templates", "routes/api.workflow-templates.tsx"),
  route("api/workflow-execute", "routes/api.workflow-execute.tsx"),
  route("editor", "routes/editor.tsx"),
] satisfies RouteConfig;
